# Generated by Django 5.1.5 on 2025-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_link_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='painel',
            field=models.BooleanField(default=False),
        ),
    ]
