# Generated by Django 5.1.5 on 2025-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_link_painel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='painel',
            field=models.BooleanField(default=False, verbose_name='Gostaria de adicionar este link ao painel de links? Caso não selecione esta opção, o link será exibido apenas no rodapé do site.'),
        ),
    ]
