# Generated by Django 5.1.5 on 2025-02-06 17:55

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prefeito', models.CharField(max_length=50)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefeituras', to='blog.ano')),
            ],
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pasta', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretarios', to='blog.prefeitura')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data_publicacao', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='publicacoes/imagens/')),
                ('video', models.FileField(blank=True, null=True, upload_to='publicacoes/videos/')),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='blog.secretario')),
                ('tipo_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='blog.tipopublicacao')),
            ],
        ),
    ]
