# Generated by Django 5.1.5 on 2025-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='em_destaque',
            field=models.BooleanField(default=False, verbose_name='Deseja por em destaque a publicação? Isso irá substituir a última publicação em destaque'),
        ),
    ]
