# Generated by Django 5.1.5 on 2025-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicacao_em_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
