# Generated by Django 5.1.5 on 2025-02-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_publicacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='descricao',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
