# Generated by Django 5.1.5 on 2025-02-07 15:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_publicacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='texto'),
            preserve_default=False,
        ),
    ]
