# Generated by Django 5.1.5 on 2025-02-11 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_publicacao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='data_atualiza',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data_publicacao',
            field=models.DateField(auto_now=True),
        ),
    ]
