# Generated by Django 5.1.5 on 2025-02-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_publicacao_data_atualiza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='secretario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastaAdministrativa_related', to='blog.pastaadministrativa'),
        ),
    ]
