# Generated by Django 5.1.5 on 2025-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pastaadministrativa_secretario_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
