# Generated by Django 5.1.5 on 2025-02-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_publicacao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='ocultar_titulo_carrocel',
            field=models.BooleanField(default=False, verbose_name='Selecione a opção ao publicar imagens com texto para evitar sobreposição. Isso assegura uma apresentação visual mais limpa e facilita a compreensão da informação no carrossel.'),
        ),
    ]
