# Generated by Django 5.1.5 on 2025-02-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_publicacao_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='secretario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='blog.secretario', verbose_name='Selecione o nome do secretário atualmente em exercício.'),
        ),
    ]
