# Generated by Django 5.1.5 on 2025-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_publicacao_author_alter_publicacao_secretario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='em_urgentes',
            field=models.BooleanField(default=False, verbose_name='Selecione esta opção se deseja marcar como urgente ou de última hora.'),
        ),
    ]
