# Generated by Django 5.1.5 on 2025-02-25 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_publicacao_em_urgentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopublicacao',
            name='svg',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Adicionar TAG <i> do fontawesome'),
            preserve_default=False,
        ),
    ]
