# Generated by Django 5.1.5 on 2025-02-25 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_tipopublicacao_svg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_curtida', models.DateTimeField(auto_now_add=True)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='blog.publicacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
