# Generated by Django 5.1.5 on 2025-02-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_pastaadministrativa_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastaadministrativa',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='pastaadministrativa',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='pastaadministrativa',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='pastaadministrativa',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='pastaadministrativa',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='YouTube'),
        ),
    ]
