# Generated by Django 5.1.5 on 2025-02-26 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_pastaadministrativa_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastaadministrativa',
            name='nome_filter',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
