# Generated by Django 5.1.5 on 2025-03-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_pastaadministrativa_nome_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curtida',
            name='usuario',
        ),
    ]
