# Generated by Django 5.1.5 on 2025-03-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_curtida_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_view', models.DateTimeField(auto_now_add=True)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualiza', to='blog.publicacao')),
            ],
        ),
    ]
