# Generated by Django 5.1.5 on 2025-03-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_viewspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewspost',
            name='publicacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualiza', to='blog.publicacao'),
        ),
    ]
