# Generated by Django 5.1.5 on 2025-03-07 16:27

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_viewspost_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coment', models.DateTimeField(auto_now_add=True)),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField()),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.publicacao')),
            ],
        ),
    ]
