# Generated by Django 5.1.5 on 2025-03-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='descricao',
            new_name='comentario',
        ),
    ]
