# Generated by Django 5.1.5 on 2025-03-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_descricao_comentarios_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ['-data_publicacao']},
        ),
    ]
