# Generated by Django 5.1.5 on 2025-03-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_publicacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastaadministrativa',
            name='prefeitura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefeitura_related_pasta', to='blog.prefeitura'),
        ),
    ]
