# Generated by Django 5.1.5 on 2025-03-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_escola_projetopoliticopedagogico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembroConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='blog.conselho')),
            ],
        ),
        migrations.CreateModel(
            name='ReuniaoConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pauta', models.TextField()),
                ('ata', models.FileField(blank=True, null=True, upload_to='atas_conselho/')),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='blog.conselho')),
            ],
        ),
    ]
