# Generated by Django 5.1.5 on 2025-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_conselho_membroconselho_reuniaoconselho'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefeitura',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link | URL'),
        ),
    ]
