# Generated by Django 5.1.5 on 2025-04-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_secretario_email_secretario_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='secretario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='secretario',
            name='telefone',
        ),
    ]
